// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvRUaxJoH2u0E19Ml-mCwXdT9ZZrRTfBw',
    appId: '1:614946816429:web:0629d4abfbeb682930a124',
    messagingSenderId: '614946816429',
    projectId: 'fragrancecollection-d939d',
    authDomain: 'fragrancecollection-d939d.firebaseapp.com',
    storageBucket: 'fragrancecollection-d939d.firebasestorage.app',
    measurementId: 'G-XZKK414PZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALOcIXMZfMa6aLhU50WiDsshji7b28TXw',
    appId: '1:614946816429:android:0033a9e124455bc430a124',
    messagingSenderId: '614946816429',
    projectId: 'fragrancecollection-d939d',
    storageBucket: 'fragrancecollection-d939d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8bisp-OJ9LN-yJY9Xqu2C_twrEyml78c',
    appId: '1:614946816429:ios:83da930dd75b091430a124',
    messagingSenderId: '614946816429',
    projectId: 'fragrancecollection-d939d',
    storageBucket: 'fragrancecollection-d939d.firebasestorage.app',
    iosBundleId: 'com.example.fragranceCollectionManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8bisp-OJ9LN-yJY9Xqu2C_twrEyml78c',
    appId: '1:614946816429:ios:83da930dd75b091430a124',
    messagingSenderId: '614946816429',
    projectId: 'fragrancecollection-d939d',
    storageBucket: 'fragrancecollection-d939d.firebasestorage.app',
    iosBundleId: 'com.example.fragranceCollectionManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvRUaxJoH2u0E19Ml-mCwXdT9ZZrRTfBw',
    appId: '1:614946816429:web:a1e94239ba3263f030a124',
    messagingSenderId: '614946816429',
    projectId: 'fragrancecollection-d939d',
    authDomain: 'fragrancecollection-d939d.firebaseapp.com',
    storageBucket: 'fragrancecollection-d939d.firebasestorage.app',
    measurementId: 'G-9204X8HM4S',
  );
}
